---


- name: Copy server binary
  copy:
    src: "{{ playbook_dir }}/repos/bleveexplorer/bin/bleve-explorer"
    dest: "/usr/local/bin/"
    mode: "0755"

- name: Create /etc/bleveexplorer dir
  file:
    path: "/etc/bleveexplorer"
    state: "directory"

- name: Create systemd unit file
  template:
    src:  "bleveexplorer-systemd.j2"
    dest: "/etc/systemd/system/bleveexplorerd.service"
  when: ansible_service_mgr == "systemd"

- name: Start Service
  service:
    name: bleveexplorerd
    enabled: yes

- name: Start Service
  service:
    name: bleveexplorerd
    state: restarted
